version: '3.8'

services:

  # item-services:
  #   image: itemservice:latest
  #   ports: 
  #     - "8080:8080"
  #   networks:
  #     backend:
  #       aliases:
  #         - "item-service" 
  #   depends_on:
  #     - db

  db:
    image: mysql:8.4.2
    container_name: db-server
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: item_db
      TZ: 'Asia/Seoul'
    
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:


networks:
  backend:
    driver: bridge


