server:
  port: 8080

logging:
  file:
    name: logs/api.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    '[com.mzc.item_service]': debug
 

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/item_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # none, create
    show-sql: true      # 실행되는 SQL문을 화면에 출력
    properties:         
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
